spring:
    application:
        name: libraryapi
    datasource:
        url: jdbc:postgresql://localhost:5432/library
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true